### ISSUE TITLE
[WORKAROUND]: New Config UI (2.0.0 and above) causes Push Notification to not work properly

### ISSUE THREAD

**Issue by andypburke** [homebridge-plugins/homebridge-eufy-security#59]
### What happened?

Push notifications was working well but now don't work after upgrading to version 2.0. I can't see any settings to change to fix this.  Any ideas?

### Device Type

Doorbell (Supported)

### Plugin Version

v2.0.x (Supported)

### HomeBridge Version

v1.4.x (Supported)

### NodeJS Version

v16 (Supported)

### Operating System

Raspbian 10+ (Supported)

### Relevant log output

```shell
[6/1/2022, 8:00:20 AM] [EufySecurity-2.0.0] WARN:  Push Closed!
[6/1/2022, 8:00:20 AM] [EufySecurity-2.0.0] INFO:  Finished shutdown!
[01/06/2022, 08:00:25] [homebridge-eufy-security] Child bridge process ended
[01/06/2022, 08:00:25] [homebridge-eufy-security] Process Ended. Code: 143, Signal: null
[01/06/2022, 08:00:31] [Apple TV 4K] State of Apple TV 4K is: true
[01/06/2022, 08:00:32] [homebridge-eufy-security] Restarting Process...
[01/06/2022, 08:00:34] [homebridge-eufy-security] Launched child bridge with PID 11720
[01/06/2022, 08:00:36] Registering platform 'homebridge-eufy-security.EufySecurity'
[01/06/2022, 08:00:36] [homebridge-eufy-security] Loaded homebridge-eufy-security v2.0.0 child bridge successfully
[01/06/2022, 08:00:36] Loaded 1 cached accessories from cachedAccessories.0E35953ECB1A.
[6/1/2022, 8:00:36 AM] [EufySecurity-2.0.0] WARN:  warning: planned changes, see https://github.com/homebridge-eufy-security/plugin/issues/1
[6/1/2022, 8:00:36 AM] [EufySecurity-2.0.0] INFO:  Country set: GB
[6/1/2022, 8:00:36 AM] [EufySecurity-2.0.0] INFO:  Finished initializing!
[01/06/2022, 08:00:36] Homebridge v1.4.1 (HAP v0.10.2) (homebridge-eufy-security) is running on port 59551.
[6/1/2022, 8:00:42 AM] [EufySecurity-2.0.0] INFO:  You're using guest admin account with this plugin! This is recommanded way!
[6/1/2022, 8:00:42 AM] [EufySecurity-2.0.0] INFO:  Updating accessory: Eufy Homebase
[6/1/2022, 8:00:43 AM] [EufySecurity-2.0.0] INFO:  Adding new bridged accessory: Front Door
[01/06/2022, 08:00:43] Front Door 27CE is running on port 43139.
[01/06/2022, 08:00:43] Please add [Front Door 27CE] manually in Home app. Setup Code: 397-53-293
```

**Comment by andypburke** [comment]
yes nothing in Common Issues

**Comment by thieren** [comment]
Hi @andypburke 

You mean push notifications from Homekit, right?

I have experienced a similar behavior from time to time. But could not find where it is caused.

Have you tried to restart homebridge altogether? For me this resolves this issue in general.

From your log I cannot see where a event is detected (motion, doorbell ring, ...) but my findings suggest that the plugin is doing it's job as planned but the informations seems to get lost somewhere on the way to homebridge or HomeKit.

Please let me know, if restarting helps.

**Comment by thieren** [comment]
Hi again

the problem seems to lie with the new config ui. This can interfere with the connection to the eufy cloud and in the end be the cause of failing push notifications.

I have added a section to the common issues to inform about this. The general workaround as of now would be to restart the plugin every time you entered the config ui - regardless of any setting being changed or not.

Way to reproduce:

- Open config ui a few times over the course of a day and close it after the device list was loaded.
- After a while (for some users after the very first time already) no push notifications will reach the plugin (no motion, ring events, ...)
- After a restart everything works again

@lenoxys For the time being I don't see if there could anything be done about this. Since we need the extra connection to setup the config wizard accordingly.
But even if the plugin-ui-utils do provide the necessary interfaces I believe a large part of the config ui would have to be rewritten.

**Comment by andypburke** [comment]
Thanks @thieren - I did this and it seemed to work, although it took about 10 seconds before the notification appeared and without a thumbnail.  Anything I can do to resolve that?

**Comment by thieren** [comment]
> thanks. I got it working again. just changed the config (didn't seem to matter what setting) and that seems to have fixed it. All a bit weird though.

Yeah. Just found the bug. But that's a completely other issue. Will fix this in the next beta.

**Comment by lenoxys** [comment]
hey @thieren, maybe it's related here see beta.9

**Comment by thieren** [comment]
Hey @lenoxys 

> hey @thieren, maybe it's related here see beta.9

Unfortunately this didn't fix the issue. Push notifications will still stop working if you open the config ui and list devices.
Furthermore there is now an error toast message when clicking on 'List Devices':

![Bildschirmfoto 2022-06-07 um 14 34 00](https://user-images.githubusercontent.com/22128659/172381484-a55e418e-0937-4565-9396-1154a5bfd5e1.png)

And in the log following errors appear:

```shell
[7.6.2022, 14:33:59] [Homebridge UI] [homebridge-eufy-security] Incoming Request: /init
[7.6.2022, 14:33:59] [Homebridge UI] [homebridge-eufy-security] Incoming Request: /getStations
[7.6.2022, 14:33:59] [Homebridge UI] [homebridge-eufy-security] [2.0.1-beta.10] INFO:  Need to refresh the devices list
[7.6.2022, 14:33:59] [Homebridge UI] [homebridge-eufy-security] TypeError: Cannot read properties of undefined (reading 'isConnected')
    at UiServer.getStations (./dev/homebridge-eufy-security/homebridge-ui/server.js:303:17)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async UiServer.processRequest (./dev/homebridge-eufy-security/node_modules/@homebridge/plugin-ui-utils/dist/server.js:75:30)
[7.6.2022, 14:34:00] [Homebridge UI] [homebridge-eufy-security] [2.0.1-beta.10] INFO:  connected!
[7.6.2022, 14:34:00] [Homebridge UI] [homebridge-eufy-security] Incoming Request: /getStations
[7.6.2022, 14:34:00] [Homebridge UI] [homebridge-eufy-security] [2.0.1-beta.10] INFO:  Need to refresh the devices list
[7.6.2022, 14:34:04] [Homebridge UI] [homebridge-eufy-security] [2.0.1-beta.10] INFO:  Connected to station T8010******** on host **.**.**.** and port 15180
[7.6.2022, 14:34:04] [Homebridge UI] [homebridge-eufy-security] [2.0.1-beta.10] ERROR: Error DuplicateDeviceError: Device with this serial T8210********** exists already and couldn't be added again!
    at EufySecurity.addDevice (./dev/homebridge-eufy-security/node_modules/eufy-security-client/build/eufysecurity.js:252:19)
    at ./dev/homebridge-eufy-security/node_modules/eufy-security-client/build/eufysecurity.js:461:26
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Promise.all (index 0)
[7.6.2022, 14:34:04] [Homebridge UI] [homebridge-eufy-security] [2.0.1-beta.10] INFO:  You're using guest admin account with this plugin! This is recommanded way!
```

**Comment by lenoxys** [comment]
Hum shame, though it was.

I do init early on this stage to avoid such error but when doing this you might generate new token but if the plugin isn't restarted it will play with the old one. UI and Plugin are working in //.

We need to find a way to force the plugin to use the new ones.

**Comment by lenoxys** [comment]
Or maybe list devices should reflect the cached ones and if user want to refresh it will need to redo the whole process that way it won't challenge anything from Eufy cloud API until user force it.

**Comment by thieren** [comment]
> Or maybe list devices should reflect the cached ones and if user want to refresh it will need to redo the whole process that way it won't challenge anything from Eufy cloud API until user force it.

That was exactly what I was thinking right now. But don't know how much work this is (therefore the estimation that this could mean a larger change).

At least we have a workaround until we get to it.

**Comment by JonoHaysom** [comment]
whats the workaround? im on beta 2 and still get this warning. 

[6/12/2022, 8:00:30 AM] [EufySecurity-2.0.1-beta.12] WARN:  Push Closed!

**Comment by thieren** [comment]
Hey @JonoHaysom 

your issue seems to be of another origin.

For me the "Push Closed!" Warning is normal but actually will only print one time before a few seconds later the "Push Connect" message appears.
These messages are passed through from the eufy-security-client library which is used by the plugin to communicate with the eufy cloud. As far as I know the plugin does nothing to force these messages and so the problem seems to lie in the connection to the cloud for you. Where exactly is impossible to know for now.

To be sure you can test with a little tool from me: https://github.com/thieren/eufy-test-client
Follow the instructions to set it up and just connect. You should see the same `Push Closed` event in the log after a few seconds. If there is also no following 'Push Connect` then it proofs that this has nothing to do with the plugin but with the underlying connection to the cloud. Maybe the author of the eufy-security-client could help in this case.


Regarding your actual question: The Workaround is now described in the common issue section https://github.com/homebridge-eufy-security/plugin/wiki/Common-Issues#push-notification-issues

But as said I don't believe that this will help you since your problem seems to persist even after a plugin restart.

**Comment by jhaleit** [comment]
I don't know if this is the same problem, but... Every time I try to change the alarm setting I have to open the eufy app on my phone for the changes to take effect. If I don't do this the process with keep timing out..

**Comment by thieren** [comment]
Hey @jhaleit 

No this sounds like #38 and is most likely not in the scope of this plugin.
There is an issue at eufy-security-client (https://github.com/bropat/eufy-security-client/issues/161) that's hopefully dealing with this.

**Comment by thieren** [comment]
This issue should be resolved with the latest beta and redesign of the config ui.

There still will be issues if you login via the config ui, but now it will not happen automatically and the user will be warned beforehand that a restart is needed afterwards.
